<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
//"swatchRenderer": {
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="swatch-opt" data-role="swatch-options"></div>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "SwatchRendererFix": {
                "jsonConfig": <?php /* @escapeNotVerified */ echo $swatchOptions = $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?php /* @escapeNotVerified */
                    echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar('gallery_switch_strategy',
                    'Magento_ConfigurableProduct') ?: 'replace'; ?>",
<?php
/**
 * 2019-03-25 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * 1) «Upgrade Magento 2 from 2.1.9 to 2.3.0»: https://www.upwork.com/ab/f/contracts/21810726
 * 2) This code is needed to show swatches on the frontend product pages.
 * It is similar to: https://mage2.pro/t/5862
 * 3) I use the code from the standard template: https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Swatches/view/frontend/templates/product/view/renderer.phtml#L22
 */
?>
                "jsonSwatchImageSizeConfig": <?php /* @noEscape */ echo $block->getJsonSwatchSizeConfig() ?>
            }
        },
<?php
/**
 * 2019-03-25 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * 1) «Upgrade Magento 2 from 2.1.9 to 2.3.0»: https://www.upwork.com/ab/f/contracts/21810726
 * 2) This code is needed to show swatches on the frontend product pages.
 * It is similar to: https://mage2.pro/t/5862
 * 3) I use the code from the standard template: https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Swatches/view/frontend/templates/product/view/renderer.phtml#L25-L25
 */
?>
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
