<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$pCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
$themeHelper = $this->helper('Magento\Theme\Helper\Theme');
if($themeHelper->isModuleOutputEnabled('TemplateMonster_ThemeOptions')):
    $themeOptionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
    $themeOptions = true;
else:
    $themeOptions = false;
endif;
?>
<?php if (!$pCollection->count()): ?>
    <div class="message info empty"><div><?= __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = $themeOptions ? $themeOptionsHelper->getCategoryShowDesc($viewMode) : false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = $themeOptions ? $themeOptionsHelper->getCategoryShowDesc($viewMode) : false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= $viewMode; ?> products-<?= $viewMode; ?> layout_1">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $p \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($pCollection as $p): ?>
                <?=($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info <?php if (!$p->getIsSalable()): ?> product-item-info-hide <?php endif; ?>" data-container="product-grid" itemscope itemtype="//schema.org/product">
                    <?php
					/**
					 * 2018-03-14 Dmitry Fedyuk https://mage2.pro/u/dmitry_fedyuk
					 * https://www.upwork.com/d/contracts/19688378
					 * https://freelancehunt.com/mailbox/read/thread/2321063
					 */
					$dfPrice = $block->getProductPrice($p); /** @var string $dfPrice */
					/** @var string $dfName */
					$dfName = $_helper->productAttribute($p, $p->getName(), 'name');
                    $productImage = $block->getImage($p, $image);
                    ?>
					<div class='product details product-item-details df-mobile-only'>
						<?= $dfPrice ?>
						<strong class="product name product-item-name" itemprop="name">
							<a class="product-item-link"
							   href="<?= $p->getProductUrl() ?>"
							><?= $dfName ?></a>
						</strong>
					</div>
					<?php
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
<!-- 2018-09-03 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
"Move the «Add to Wish List» button to the same position as in victoriassecret.com":
https://github.com/frugue/core/issues/30 -->
					<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
						<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
							<?php echo $addToBlock->setProduct($p)->getChildHtml(); ?>
						<?php endif; ?>
					</div>						
                    <?php // Product Image ?>
                    <a href="<?= $p->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1" itemprop="url">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
						<div class='df-desktop-only'>
							<?= $dfPrice ?>
							<strong class="product name product-item-name" itemprop="name">
								<a class="product-item-link"
								   href="<?= $p->getProductUrl() ?>"
								><?= $dfName ?></a>
							</strong>
						</div>
                        <?php $pNameStripped = $block->stripTags($p->getName(), null, true); ?>
                        <?php if ($showDescription):?>
                            <div class="product description product-item-description" itemprop="description">
                                <?= $_helper->productAttribute($p, $p->getShortDescription(), 'short_description') ?>
                                <a href="<?= $p->getProductUrl() ?>" title="<?= $pNameStripped ?>"
                                   class="action more"><?= __('Learn More') ?></a>
                            </div>
                        <?php endif; ?>
                        <?php echo $block->getProductDetailsHtml($p); ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($p->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($p); ?>
                                        <form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?= __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($p->getIsSalable()): ?>
                                            <div class="stock available"><span><?= __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($block->getMode() == 'grid'): ?>
                                    <?php echo $block->getReviewsSummaryHtml($p, $templateType); ?>
                                <?php endif; ?>
                            </div>
                            <?php if ($block->getMode() == 'list'): ?>
                                <?php echo $block->getReviewsSummaryHtml($p, $templateType); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($pCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
